name: Build ETL Component from Ab Initio Graphs

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build ETL component
        run: |
          python3 buildctl.py

      - name: Package TAR
        run: |
          tar -czf etl-component-${{ github.ref_name }}.tar.gz etl-component/

      - name: Upload TAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: etl-component-tar
          path: etl-component-*.tar.gz

      - name: Build OCI image
        run: |
          docker build -t etl-component:${{ github.ref_name }} .

      - name: Login to Docker Hub
        run: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
              -u ${{ secrets.DOCKERHUB_USERNAME }} \
              --password-stdin

      - name: Tag and push image
        run: |
              docker tag etl-component:${{ github.ref_name }} \
                bindumounica87/etl-component:${{ github.ref_name }}
          
              docker push bindumounica87/etl-component:${{ github.ref_name }}